"""empty message

Revision ID: 1e3b58bc06a1
Revises: 6fc1b74a5f2c
Create Date: 2025-10-01 21:19:39.266970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3b58bc06a1'
down_revision = '6fc1b74a5f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cesta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=200), nullable=True))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    with op.batch_alter_table('cesta', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
